const menuItems = [
    {
        id:"classic",
        type:"breakfast",
        name:"Classic Breakfast",
        price:11.99,
        description:"Two fresh eggs cooked your way, toasted bread, and your choice of crispy bacon, sausage, or smoked ham",
        contains:"eggs, wheat(bread), pork, milk(butter).",
        MayContain:"soy.",
        cals:"550-850",
        kids:false,
        pairsWith:["coffee", "juice", "tea"]
        

    },
    {
        id:"double-egg",
        tyepe:"breakfast",
        name:"Double Egg Breakfast",
        price:3.49,
        description:"Two farm-fresh eggs cooked to your preference",
        contains:"eggs",
        cals:"140-220",
        kids:false,
        pairsWith:["coffee", "juice", "tea"]
        
    },
    {
        id:"half classic",
        type:"breakfast",
        name:"Half Classic",
        price:8.49,
        description:"One fresh egg, toasted bread, and your choice of crispy bacon, sausage, or smoked ham.",
        contains:"eggs, wheat (toast), milk (butter), pork.",
        MayContain:"soy.",
        cals:"350-550",
        kids:false,
        pairsWith:["coffee", "juice", "tea"]
    },
    {
        id:"pancake",
        type:"breakfast",
        name:"Pancake Breakfast",
        price:7.99,    
        description:"One oversized fluffy buttermilk pancake served with whipped butter and maple syrup",
        contains:"wheat,eggs,milk",
        cals:"600-850",
        kids:false,
        pairsWith:["juice", "coffee", "tea"]
    },
    {
        id:"double-pancake",
        type:"breakfast",
        name:"Double Pancake Breakfast",
        price:12.99,
        description:"Two oversized fluffy buttermilk pancakes served with whipped butter and maple syrup",
        contains:"wheat,eggs,milk",
        cals:"1,000-1,400",
        kids:false,
        pairsWith:["juice", "coffee", "tea"]
    },
    {
        id:"coffee",
        type:"beverage",
        name:"Coffee",
        price:3.49,
        amount:"12oz",
        description:"Freshly brewed regular or decaf coffee with complimentary refills",
        contains:"Coffee grounds",
        cals:"5-10",
        kids:false,
        pairsWith:[""]
    },
    {
        id:"milk",
        type:"beverage",
        name:"Milk (white or chocolate)",
        price:3.49,
        amount:"12oz",
        description:"Cold white or chocolate milk served in a kid-sized cup",
        contains:"Dairy",
        cals:"100-160",
        kids:false,
        pairsWith:[""]
    },
    {
        id:"hot chocolate",
        type:"beverage",
        name:"Hot Chocolate",
        price:3.99,
        amount:"12oz",
        description:"Rich, creamy hot chocolate topped with whipped cream",
        contains:"Milk, dairy, soy",
        cals:"200-350",
        kids:false,
        pairsWith:[""]
    },
    {
        id:"lemonade",
        type:"beverage",
        name:"Lemonade",
        price:3.99,
        amount:"12oz",
        description:"Refreshing lemonade made with lemon juice, water, and sugar. Free refills",
        contains:"No major allergens",
        cals:"150-250",
        kids:false,
        pairsWith:[""]
    },
    {
        id:"juice",
        type:"beverage",
        name:"Juice (orange, grape, apple, or cranberry)",
        price:3.99,
        amount:"12oz",
        description:"Choose from orange, apple, grape, or cranberry juice. Made from fruit juice concentrates",
        contains:"No major allergens",
        cals:"100-180",
        kids:false,
        pairsWith:[""]
    },
    {
        id:"churros",
        type:"dessert",
        name:"Churros",
        price:[
            {NumOfFood:1, Price:2.49},
            {NumOfFood:2, Price:4.49},
            {NumOfFood:4, Price:7.99},
            {NumOfFood:8, Price:14.99}
        ],
        description:"One, Two, Four, or Eight warm churro(s) coated in cinnamon sugar. Served with chocolate dipping sauce upon request",
        contains:"wheat. Chocolate sauce contains milk and soy",
        cals:"150-2,000",
        kids:false,
        pairsWith:[""]
    },
    {
        id:"cinnamon breakfast cake",
        type:"dessert",
        name:"Cinnamon Breakfast Cake",
        price:[
            {SizeOfFood:"Small", price:6.99},
            {SizeOfFood:"Large", price:7.99}
        ],
        description:"Warm cinnamon breakfast cake topped with vanilla glaze and served with whipped butter",
        contains:"wheat, eggs, milk",
        cals:"450-700",
        kids:false,
        pairsWith:[""]
    },
    {
        id:"classic breakfast",
        type:"breakfast",
        name:"Classic Breakfast kids",
        price:5.99,
        description:"One fresh egg, half a slice of toasted bread, and your choice of crispy bacon, sausage, or smoked ham",
        contains:"eggs, wheat (toast), milk (butter), pork",
        MayContain:"Soy",
        cals:"300-450",
        kids:true,
        pairsWith:["juice,coffee,tea"]
    },
    {
        id:"egg & choice of meat",
        type:"breakfast",
        name:"Egg & Choice of Meat Breakfast",
        price:4.99,
        description:"One fresh egg served with your choice of crispy bacon, sausage, or smoked ham",
        contains:"egg, pork",
        cals:"250-400",
        kids:true,
        pairsWith:["juice,coffee,tea"]
    },
    {
        id:"French Toast",
        type:"breakfast",
        name:"French Toast Breakfast",
        price:[
            {NumOfFood:2, price:4.99},
            {NumOfFood:4, price:6.99}
        ],
        description:"Two or Four golden French toast sticks served with butter and maple syrup",
        contains:"wheat, eggs, milk",
        cals:"250-700",
        kids:true,
        pairsWith:["milk, hot chocolate, coffee"]
    },
    {
        id:"milk",
        type:"beverage",
        name:"Milk (white or chocolate) kids",
        price:2.49,
        amount:"8oz",
        description:"Cold white or chocolate milk served in a kid-sized cup",
        contains:"milk",
        cals:"100-160",
        kids:true,
        pairsWith:[""]
    },
    {
        id:"juice",
        type:"beverage",
        name:"Juices kids",
        price:2.49,
        amount:"8oz",
        description:"Choose from orange, apple, grape, or cranberry juice. Made from fruit juice concentrates",
        contains:"No major allergens",
        cals:"100-180",
        kids:true,
        pairsWith:[""]
    },
    {
        id:"hot chocolate",
        type:"beverage",
        name:"Hot Chocolate kids",
        price:2.99,
        amount:"8oz",
        description:"Rich, creamy hot chocolate topped with whipped cream",
        contains:"milk",
        cals:"200-350",
        kids:true,
        pairsWith:[""]
    },
    {
        id:"Mini Churros",
        type:"dessert",
        name:"mini churros (1 or 2)",
        price:[
            {NumOfFood:1, price:1.99},
            {NumOfFood:2, price:3.49}
        ],
        description:"One or Two bite-sized churro(s) coated in cinnamon sugar and served with chocolate dipping sauce",
        contains:"wheat. Chocolate sauce contains milk and soy",
        cals:"80-300",
        kids:true,
        pairsWith:["milk, hot chocolate, coffee"]
    },
    {
        id:"burger",
        type:"lunch",
        name:"Old Time Burger",
        price:12.99,
        description:"Classic beef burger topped with cheddar cheese, pickles, lettuce, tomato, diced red onions, and mustard. Served with seasoned fries.",
        contains:"wheat(bun), milk(cheese), eggs(mayonnaise),soy.",
        MayContain:"sesame (bun), cross-contact with other allergens from the kitchen",
        cals:"850-1,270",
        kids:false,
        pairsWith:[""]
    },
    {
        id:"cripers",
        type:"lunch",
        name:"Chicken Crispers",
        price:13.99,
        description:"Crispy chicken tenders served with your choice of dipping sauce and seasoned fries.",
        contains:"wheat (breading), milk (breading/batter), eggs (breading), soy.",
        MayContain:"cross-contact with other allergens from the fryer and kitchen preparation areas",
        cals:"1,080-1,420",
        kids:false,
        pairsWith:["soft drink, juice"]
    },
    {
        id:"triple-dipper",
        type:"lunch",
        name:"Triple Dipper",
        price:16.99,
        description:"a customizable appetizer sampler where you select any three signature appetizers served together in a single shared platter with matching dipping sauces.",
        cals:"1,740-3,920",
        pairsWith:[""]

    },
    {
        id:"bacon ranch",
        type:"lunch",
        name:"Bacon Ranch Quesadilla",
        price:14.99,
        description:"A grilled flour tortilla filled with crispy bacon, melted cheese, and creamy ranch dressing. Served with a side of salsa and sour cream.",
        contains:"wheat(tortilla),milk(cheese,ranch,sour cream),eggs(ranch),soy",
        MayContain:"cross-contact with gluten, dairy, and other allergens from shared cooking surfaces",
        cals:"900-1200",
        kids:false,
        pairsWith:["lemonade", "iced tea", "soda"]
    },
    {
        id:"southwest chicken",
        type:"lunch",
        name:"Southwest Chicken Bowl",
        price:16.59,
        description:"Grilled chicken served over seasoned rice with black beans, corn, fresh salsa, shredded cheese, avocado, and a drizzle of southwest ranch. Served as a hearty Tex-Mex inspired bowl",
        contains:"milk (cheese, southwest ranch), wheat (possible seasoning/sauce ingredients), eggs (ranch dressing), soy (possible sauces/seasonings).",
        MayContain:"cross-contact with gluten, dairy, and other allergens from shared kitchen equipment",
        cals:"880",
        kids:false,
        pairsWith:[""]
    },
    {
        id:"chicken caesar",
        type:"lunch",
        name:"Chicken Caesar Salad",
        price:16.59,
        description:"Grilled chicken breast served over crisp romaine lettuce with shredded Parmesan cheese, seasoned croutons, and creamy Caesar dressing",
        contains:"milk (Parmesan cheese, Caesar dressing), wheat (croutons), eggs (Caesar dressing), fish (traditional Caesar dressing may contain anchovies), soy (possible dressing ingredients).",
        MayContain:"cross-contact with gluten, dairy, and other allergens from shared kitchen preparation areas",
        cals:"540",
        kids:false,
        pairsWith:[""]
    },
    {
        id:"soft drinks",
        type:"Beverage",
        name:"Soft Drinks",
        price:3.39,
        amount:"16oz",
        description:"Choose from classic fountain favorites such as Coca-Cola, Diet Coke, Sprite, Dr Pepper, or other available soft drinks. Served chilled over ice",
        contains:"Depends on drink choice. Most soft drinks contain carbonated water, sweeteners, and flavorings",
        cals:"caffeine (cola drinks), artificial sweeteners (diet drinks).",
        kids:false,
        pairsWith:[""]
    },
    {
        id:"iced tea",
        type:"Beverage",
        name:"Iced Tea",
        price:3.79,
        amount:"12oz",
        description:"Freshly brewed black tea served chilled over ice. Available sweetened or unsweetened",
        contains:"No major food allergens",
        cals:"100",
        kids:false,
        pairsWith:[""]
    },
    {
        id:"dragonfruit lemonade",
        type:"beverage",
        name:"Dragonfruit Lemonage",
        price:4.99,
        amount:"12oz",
        description:"A refreshing blend of fresh lemonade and sweet dragonfruit flavor, served chilled over ice with a vibrant tropical taste",
        contains:"No major food allergens",
        cals:"180-280",
        kids:false,
        pairsWith:[""]
    },
    {
        id:"blackberry ice tea",
        type:"beverage",
        name:"Blackberry Ice Tea",
        price:3.79,
        amount:"12oz",
        description:"Freshly brewed iced tea blended with sweet blackberry flavor and served chilled over ice for a refreshing fruity twist",
        contains:"No major food allergens",
        cals:"80",
        kids:false,
        pairsWith:[""]
    },
    {
        id:"double fudge chocolate cake",
        type:"dessert",
        name:"Double Fudge Chocolate Cake",
        price:8.99,
        description:" A rich, moist chocolate cake layered with creamy chocolate fudge filling and topped with a decadent chocolate frosting. Served as a generous dessert slice",
        contains:"milk (fudge filling, frosting), eggs (cake), wheat (flour), soy (chocolate/frosting ingredients).",
        MayContain:"tree nuts or peanuts depending on chocolate/facility ingredients. Cross-contact with other allergens is possible in the kitchen",
        cals:"900-1,300",
        kids:false,
        pairsWith:[""]
    },
    {
        id:"cookies",
        type:"dessert",
        name:"Cookies",
        price:4.99,
        description:"Two warm, freshly baked chocolate chip cookies filled with sweet chocolate chips and served as a shareable dessert",
        contains:"wheat (flour), milk (butter/chocolate chips), eggs, soy (chocolate chips).",
        MayContain:"peanuts and tree nuts depending on chocolate and facility ingredients. Cross-contact with other allergens is possible",
        cals:"400-700",
        kids:false,
        pairsWith:[""]
    },
    {
        id:"chicken strips",
        type:"lunch",
        name:"Chicken Strips kids (1,3,5)",
        price:[
            {NumOfFood:1, price:5.49},
            {NumOfFood:3, price:6.99},
            {NumOfFood:5, price:8.49}
        ],
        description:"Crispy hand-breaded chicken strips served with your choice of dipping sauce and a kid-sized side such as fries, fruit, or vegetables",
        contains:"wheat (breading), milk (breading/batter), eggs (breading), soy (seasoning/sauce ingredients).",
        MayContain:"cross-contact with gluten, dairy, eggs, and other allergens from shared fryer oil and kitchen equipment",
        cals:"250-1,100",
        kids:true,
        pairsWith:[""]
    },
    {
        id:"hot dog",
        type:"lunch",
        name:"Hot Dog",
        price:5.99,
        description:"A grilled all-beef hot dog served on a soft toasted bun with ketchup and mustard. Served with a kid-sized side such as fries, fruit, or vegetables",
        contains:"wheat (bun), soy (possible hot dog ingredients/bun), milk (possible bun ingredients).",
        MayContain:"cross-contact with gluten and other allergens from shared cooking surfaces",
        cals:"450-700",
        kids:true,
        pairsWith:[""]
    },
    {
        id:"classic burger",
        type:"lunch",
        name:"Classic Burger kids",
        price:6.99,
        description:"A kid-sized grilled beef patty served on a toasted bun with lettuce, tomato, pickles, and your choice of ketchup or mustard. Served with a kid-sized side such as fries, fruit, or vegetables",
        contains:"wheat (bun), milk (optional cheese), soy (possible bun/seasoning ingredients).",
        MayContain:"eggs (if mayonnaise is added), sesame (bun), and cross-contact with other allergens from shared cooking surfaces",
        cals:"500-800",
        kids:true,
        pairsWith:[""]
    },
    {
        id:"lemonade",
        type:"beverage",
        name:"Lemonade kids",
        price:2.49,
        amount:"8oz",
        description:"A refreshing blend of lemon juice, water, and sugar served chilled over ice in a kid-sized cup",
        contains:"No major food allergens",
        cals:"120-180",
        kids:true,
        pairsWith:[""]
    },
    {
        id:"soft drinks",
        type:"beverage",
        name:"Soft Drinks kids",
        price:1.99,
        amount:"8oz",
        description:"A kid-sized fountain drink served chilled over ice. Choose from favorites such as Coca-Cola, Sprite, Dr Pepper, or other available soft drinks",
        contains:"Depends on drink choice. Most contain carbonated water, sweeteners, and flavorings",
        MayContain:"caffeine (cola drinks), artificial sweeteners (diet drinks).",
        cals:"0-120",
        kids:true,
        pairsWith:[""]
    },
    {
        id:"mini ice cream",
        type:"dessert",
        name:"Mini Ice Cream",
        price:2.99,
        description:"A small scoop of creamy vanilla ice cream served in a cup. Available with optional chocolate or caramel drizzle",
        contains:"milk (ice cream), eggs (ice cream base).",
        MayContain:"soy (chocolate toppings), peanuts and tree nuts depending on toppings and facility ingredients. Cross-contact with other allergens is possible",
        cals:"150-300",
        kids:true,
        pairsWith:[""]
    },
    {
        id:"classic sirloin",
        type:"dinner",
        name:"Classic Sirloin",
        price:[
            {SizeOfFood:"8oz", price:18.99},
            {SizeOfFood:"12oz", price:23.99},
            {SizeOfFood:"16oz", price:28.99}
        ],
        description:"A tender grilled sirloin steak seasoned with signature spices and cooked to your preference. Served with your choice of side, such as mashed potatoes, fries, or steamed vegetables",
        contains:"Possible milk (butter used on steak or sides) Possible soy (seasonings/marinades)",
        MayContain:"Cross-contact with wheat, dairy, soy, and other allergens from shared grills and kitchen equipment",
        cals:"600-1,500",
        kids:false,
        pairsWith:[""]
    },
    {
        id:"baby back ribs",
        type:"dinner",
        name:"Baby Back Ribs",
        price:[
            {SizeOfFood:"half rack", price:21.89},
            {SizeOfFood:"full rack", price:27.29}
        ],
        description:"Slow-cooked pork ribs brushed with a smoky barbecue sauce and grilled until tender. Served with your choice of sides, such as fries, coleslaw, or corn on the cob",
        contains:"Soy (possible in barbecue sauce) Wheat (possible in barbecue sauce or seasoning) Possible milk (butter used on sides)",
        MayContain:"Cross-contact with gluten, dairy, soy, and other allergens from shared grills and kitchen equipment",
        cals:"1,130-2,160",
        kids:false,
        pairsWith:[""]
    },
    {
        id:"cajun chicken pasa",
        type:"dinner",
        name:"Cajun Chicken Pasa",
        price:18.59,
        description:"Grilled chicken breast tossed with penne pasta in a creamy Cajun Alfredo sauce with bell peppers, onions, and Cajun spices. Served with Parmesan cheese on top",
        contains:"Wheat (pasta) Milk (Alfredo sauce, Parmesan cheese, cream) Eggs (possible in pasta) Soy (possible in sauce/seasonings)",
        MayContain:"Cross-contact with gluten, dairy, soy, and other allergens from shared kitchen equipment",
        cals:"1,070-1,390",
        kids:false,
        pairsWith:[""]
    },
    {
        id:"santa fe chicken",
        type:"dinner",
        name:"Santa Fe Chicken",
        price:17.99,
        description:"Grilled chicken breast topped with melted cheese, avocado slices, tomatoes, green onions, and a Santa Fe sauce. Served with your choice of side, such as rice, mashed potatoes, or vegetables",
        contains:"Milk (cheese, possible sauce ingredients) Soy (possible in sauces/seasonings) Possible eggs (if sauce contains mayonnaise-based ingredients)",
        MayContain:"Cross-contact with wheat, dairy, soy, and other allergens from shared grills and kitchen equipment",
        cals:"900-1,300",
        kids:false,
        pairsWith:[""]
    },
    {
        id:"ancho salmon",
        type:"dinner",
        name:"Ancho Salmon",
        price:22.59,
        description:"A grilled salmon fillet seasoned with ancho chili spices and topped with a flavorful ancho sauce. Served with your choice of side, such as rice, steamed vegetables, or mashed potatoes",
        contains:"Fish (salmon) Milk (possible butter used on salmon or sides) Soy (possible in sauces/seasonings)",
        MayContain:"Cross-contact with shellfish, wheat, dairy, soy, and other allergens from shared cooking surfaces",
        cals:"590",
        kids:false,
        pairsWith:[""]
    },
    {
        id:"strawberry lemonade",
        type:"beverage",
        name:"Strawberry Lemonade",
        price:3.79,
        amount:"12oz",
        description:"Cold, bold and thirst-quenching lemonade juiced up with real strawberries.",
        contains:"Depends on drink choice. Most contain carbonated water, sweeteners, and flavorings",
        MayContain:"Caffeine (cola drinks), artificial sweeteners (diet drinks).",
        cals:"240",
        kids:false,
        pairsWith:[""]
    },
    {
        id:"watermelon ice tea",
        type:"beverage",
        name:"Watermelon Ice Tea",
        price:4.49,
        amount:"12oz",
        description:"Freshly brewed iced tea blended with sweet watermelon flavor and served chilled over ice",
        contains:"Brewed black tea, water, watermelon flavor/purée, and sugar if sweetened",
        MayContain:"Caffeine. No major food allergens. Cross-contact is possible from shared drink equipment",
        cals:"20-220",
        kids:false,
        pairsWith:[""]
    },
    {
        id:"dragonfruit ice tea",
        type:"beverage",
        name:"Dragonfruit Ice Tea",
        price:4.49,
        amount:"12oz",
        description:"Freshly brewed iced tea blended with sweet dragonfruit flavor and served chilled over ice for a refreshing tropical drink",
        contains:"Brewed black tea, water, dragonfruit flavor/purée, and sugar if sweetened",
        MayContain:"Caffeine. No major food allergens. Cross-contact is possible from shared drink equipment",
        cals:"",
        kids:false,
        pairsWith:[""]
    },
   /*  {
        id:"",
        type:"",
        name:"",
        price:,
        amount:"",
        description:"",
        contains:"",
        cals:"",
        kids:,
        pairsWith:[""]
    },
    {
        id:"",
        type:"",
        name:"",
        price:,
        description:"",
        contains:"",
        cals:"",
        kids:,
        pairsWith:[""]
    },
    {
        id:"",
        type:"",
        name:"",
        price:,
        description:"",
        contains:"",
        cals:"",
        kids:,
        pairsWith:[""]
    },
    {
        id:"",
        type:"",
        name:"",
        price:,
        description:"",
        contains:"",
        cals:"",
        kids:,
        pairsWith:[""]
    }, */
];